{% set name = "ipypublish" %}
{% set version = "0.9.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b653a4dca829b01985cfa6744787d0d939007f3bec85067cface2f0f71812b4d

build:
  number: 0
  noarch: python
  entry_points:
    - nbpublish = ipypublish.frontend.nbpublish:run
    - nbpresent = ipypublish.frontend.nbpresent:run
    - ipubpandoc = ipypublish.filters_pandoc.main:pandoc_filters
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - bibtexparser
    - docutils
    - jinja2
    - jsonextended >=0.7
    - jsonschema
    - jupytext
    - nbconvert
    - nbformat
    - pandoc
    - panflute
    - pathlib2
    - python
    - ruamel.yaml
    - setuptools
    - shutilwhich
    - six
    - sphinx >=1.6
    - sphinxcontrib-bibtex
    - tornado <6
    - traitlets
    - typing

test:
  imports:
    - ipypublish
    - ipypublish.convert
    - ipypublish.export_plugins
    - ipypublish.filters
    - ipypublish.filters_pandoc
    - ipypublish.filters_pandoc.tests
    - ipypublish.frontend
    - ipypublish.ipysphinx
    - ipypublish.ipysphinx.css
    - ipypublish.port_api
    - ipypublish.postprocessors
    - ipypublish.preprocessors
    - ipypublish.schema
    - ipypublish.scripts
    - ipypublish.templates
    - ipypublish.templates.outline_schemas
    - ipypublish.templates.segments
    - ipypublish.tests
    - ipypublish.tests.test_files
  commands:
    - nbpublish --help
    - nbpresent --help
    - echo "a" | pandoc --filter ipubpandoc

about:
  home: https://github.com/chrisjsewell/ipypublish
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A workflow for creating and editing publication ready scientific reports, from one or more Jupyter Notebooks
  doc_url: https://ipypublish.readthedocs.io
  dev_url: https://github.com/chrisjsewell/ipypublish

extra:
  recipe-maintainers:
    - chrisjsewell
